/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2013-07-10 02:25:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/templates/footer.jsp", Long.valueOf(1371670985000L));
    _jspx_dependants.put("/templates/header.jsp", Long.valueOf(1373415583000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/base.css\" type=\"text/css\"\n");
      out.write("\tmedia=\"screen\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/skeleton.css\" type=\"text/css\"\n");
      out.write("\tmedia=\"screen\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout.css\" type=\"text/css\"\n");
      out.write("\tmedia=\"screen\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\"\n");
      out.write("\tmedia=\"screen\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Recommender</title>\n");
      out.write("</head>");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div align=\"left\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\" align=\"left\">\n");
      out.write("\t\t\t<h1>Recommender</h1>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t<form action=\"Login\" method=\"get\"> <!--  Normally this is POST -->\n");
      out.write("\t\t\t\t\t<p id=\"smallheader\">Returning Users</p>\n");
      out.write("\t\t\t\t\t<div id=\"descriptor\">Unique ID:</div>\n");
      out.write("\t\t\t\t\t&nbsp;\n");
      out.write("\t\t\t\t\t<div id=\"loginbar\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"userid\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div id=\"loginbutton\">\n");
      out.write("\t\t\t\t\t\t<button name=\"subject\" type=\"submit\" value=\"login\">Login</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<button onClick=\"unhide(); hideButton(); hideMsg();\" id=\"displaynewuserbutton\">New User?</button>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\tfunction unhide() {\n");
      out.write("\t\t\t\tvar hiddenDiv = document.getElementById('newuser');\n");
      out.write("\t\t\t\thiddenDiv.style.display = 'inline';\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tfunction hideButton() {\n");
      out.write("\t\t\t\tvar button = document.getElementById('displaynewuserbutton');\n");
      out.write("\t\t\t\tbutton.style.display = 'none';\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tfunction hideMsg() {\n");
      out.write("\t\t\t\tvar msgdiv = document.getElementById('messagediv');\n");
      out.write("\t\t\t\tmsgdiv.style.display = 'none';\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\n");
      out.write("\t\t<!-- This form allows for new user creation, and remains hidden until user activation. -->\n");
      out.write("\t\t<div class=\"row\" style=\"display:none\" id=\"newuser\">\n");
      out.write("\t\t\t<div align=\"left\">\n");
      out.write("\t\t\t\t<form action=\"CreateUser\" method=\"post\">\n");
      out.write("\t\t\t\t\t<p id=\"smallheader\">New Users</p>\n");
      out.write("\t\t\t\t\t<div id=\"descriptor\">Unique ID:</div>\n");
      out.write("\t\t\t\t\t<div id=\"loginbar\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"userid\"><br>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div id=\"descriptor\">Name:</div>\n");
      out.write("\t\t\t\t\t<div id=\"loginbar\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"realname\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div id=\"loginbutton\">\n");
      out.write("\t\t\t\t\t\t<button name=\"subject\" type=\"submit\" value=\"create\">Create\n");
      out.write("\t\t\t\t\t\t\tNew User</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"row\" id=\"messagediv\">\n");
      out.write("\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
